### ISSUE TITLE
Filename incorrect for new 5.5a4 version - locale now "ALL"

### ISSUE THREAD

**Issue by saltthefries** [micahflee/torbrowser-launcher#203]
Hello - I'm getting 404 errors when launching the torbrowser-launcher as it attempts to download TBB 5.5a4-hardenened. I'm using Debian Jessie, using the version 0.2.0-1 from backports.
It looks like this new version includes all supported languages, so the file name has changed slightly.
https://blog.torproject.org/blog/tor-browser-55a4-hardened-released

It looks like the code is deriving the filename in line 113 of torbrowser_launcher/common.py
If I have some spare time before someone else fixes it, I'll write a pull request.

**Comment by DonnchaC** [comment]
+1

**Comment by DonnchaC** [comment]
The cause of the issue (#202) is resolved in master now. If you have hit this bug you will have an incorrect Tor browser version in your `.config/torbrowser/settings.json` file.

You should replace the value:

    "latest_version": "5.5a4-hardened"

with:

    "latest_version": "5.0.4"

You should then be able to initiate an update as normal

**Comment by micahflee** [comment]
Yup. Thanks @DonnchaC. I just released 0.2.1 last night, which resolves this bug. It hasn't yet made it into Debian, but hopefully it will soon.

**Comment by mikecardwell** [comment]
FYI, for anyone using Debian, you have to change:

> S'5.5a4-hardened'

To:

> S'5.0.4'

In:

> ~/.config/torbrowser/settings

**Comment by mikecardwell** [comment]
Oh hang on. That still doesn't fix it. Downloads the right version now but then tries to execute:

> ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser

Which doesn't exist. You then need another fix, which is to do this:

> cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US
> ln -s Browser/start-tor-browser .
