### ISSUE TITLE
SIGNATURE VERIFICATION FAILED - Error Code: EB774491D9FF06E2: No public key

### ISSUE THREAD

**Issue by fedorahead** [micahflee/torbrowser-launcher#378]
Fedora 29 x6. Execution of 'sudo dnf install torbrowser-launcher' appeared successful. Execution of 'torbrowser-launcher' results in downloading of file followed by window presenting 'SIGNATURE VERIFICATION FAILED - Error Code: EB774491D9FF06E2: No public key' message.

![image](https://user-images.githubusercontent.com/11986918/48441949-6ef9cf80-e752-11e8-8f0d-7398220dcb73.png)

**Comment by fedorahead** [comment]
This is a very odd problem. I have (so far) been able to install Tor (with a few problems) on one host machine, but this problem persists on another.

**Comment by rorbudd** [comment]
Is there a solution - where can it be found?

**Comment by rogers0** [comment]
@rorbudd This should be already fixed by latest version, v0.3.1.

**Comment by knstn-project** [comment]
I can confirm the same error on Fedora 29 x86_64. Tried to install an hour before, and i get the same error.

**Comment by micksmothers** [comment]
Still happening. Fresh install of torbrowser-launcher on Fedora 29

**Comment by micahflee** [comment]
See https://github.com/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188
